import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kadya Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <h1>Kadya Store</h1>
      </header>

      <main className={styles.main}>
        <h2>Introduction</h2>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum
          recusandae repellat nam ipsam nesciunt quod similique consequuntur,
          ipsum ducimus animi amet debitis perferendis, doloremque eaque
          delectus rerum commodi autem mollitia?
        </p>
      </main>

      <footer className={styles.footer}>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde
          voluptatum esse vel.
        </p>
      </footer>
    </div>
  );
}
