// Next.js components
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// Custom components
import styles from "./Home.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>متجر بقالة</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>متجر بقالة</h1>
      </header>
      <Appbar></Appbar>

      <main className={styles.main}>
        <h2>Introduction</h2>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum
          recusandae repellat nam ipsam nesciunt quod similique consequuntur,
          ipsum ducimus animi amet debitis perferendis, doloremque eaque
          delectus rerum commodi autem mollitia?
        </p>
        <h3>روابط الصفحات</h3>
        <ul>
          <li>
            <Link href="/login">
              <a className="link">تسجيل الدخول</a>
            </Link>
          </li>
          <li>
            <Link href="/register">
              <a className="link">إنشاء حساب</a>
            </Link>
          </li>
          <li>
            <Link href="/account">
              <a className="link">الحساب</a>
            </Link>
          </li>
          <li>
            <Link href="/cart">
              <a className="link">العربة</a>
            </Link>
          </li>
          <li>
            <Link href="/favorite">
              <a className="link">المفضلة</a>
            </Link>
          </li>
          <li>
            <Link href="/search">
              <a className="link">البحث</a>
            </Link>
          </li>
        </ul>
      </main>

      <Footer></Footer>
    </div>
  );
}
